config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :edit, :update] 
    get 'users/search', to: 'users#search'
  end

  root to: 'homes#top'
  get "home/about" => "homes#about", as: 'about'
  get 'searches/search'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'shelter' => 'users#shelter', as: 'shelter'
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'
    patch 'withdraw', to: 'users#withdraw', as: 'withdraw'
  end

  resources :articles, only: [:index, :show, :edit, :new, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy, :show]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :notifications, only: [:index, :destroy]

  resources :chats, only: [:index, :show, :create]

  # 問い合わせ
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_one_attached :image

  # いいね・コメント機能
  has_many :favorites, dependent: :destroy
  has_many :favorite_articles, through: :favorites, source: :article
  has_many :post_comments, dependent: :destroy

  # 通知機能
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy # 自分からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy # 相手からの通知

  # フォロー・フォロワー機能
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # DM機能
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  # バリデーション
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :name_kana, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :address, presence: true
  validates :category, presence: true
  validates :telephone_number, length: { in: 6..11 }

  enum category: { private_user: 0, shelter: 1 }

  # ユーザー情報変更の際に現在のパスワードはパラメーター内で不要となり、
  # かつパスワードとパスワードの確認を空とした場合、パスワードの更新はなされなくなる
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end

  # 投稿画像がない場合は"noimage.png"を表示させる
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.png')
      image.attach(io: File.open(file_path), filename: 'noimage.png', content_type: 'image/png')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # フォローする時
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外す時
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているのか判定
  def following?(user)
    followings.include?(user)
  end

  # フォロー通知
  def create_notification_follow!(current_user)
    # すでに通知が作成されているか確認
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # admin検索(カテゴリの指定なしの場合)
  def self.searches(search)
      User.where(['name LIKE ?', "%#{search}%"])
  end

  # admin検索(カテゴリの指定ありの場合)
  def self.looks(category,word)
    if category == "private_user"
      @user = User.where("name LIKE?", "%#{word}%").and(where(category: "private_user"))
    else
      @user = User.where("name LIKE?", "%#{word}%").and(where(category: "shelter"))
    end
  end
  
  def self.guest
    find_or_create_by!(name: 'ゲストユーザー', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
      user.name_kana = "ゲストユーザー"
      user.nickname = "ゲストユーザー"
      user.telephone_number = "00000000000"
      user.address = "日本"
      user.category = "private_user"
    end
  end



end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user

  def index
    @users = User.all.order(params[:sort]).with_attached_image.includes([:image_attachment]).page(params[:page]).per(6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_root_path
  end

  def search
    @category = params[:category]
    if @category != ""
      @users = User.looks(params[:category],params[:word]).order(created_at: :desc).with_attached_image.includes([:image_attachment]).page(params[:page]).per(6)
    else
      @users = User.searches(params[:word]).order(created_at: :desc).with_attached_image.includes([:image_attachment]).page(params[:page]).per(6)
    end
  end
  
  def name_kana_desc
    @users = User.all.order(params[:sort]).with_attached_image.includes([:image_attachment]).page(params[:page]).per(6)
  end


  private

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def user_params
    #admin=trueに書き換えられないようにadminをpermitに入れない
    params.require(:user).permit(:category, :name, :name_kana, :nickname, :telephone_number, :address, :is_deleted)
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # deviseでアカウント情報を変更する際に現在のパスワード入力を省くメソッド
  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  # 更新後のパスを指定。マイページに戻るように設定。
  def after_update_path_for(resource)
    user_path(@user.id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_state, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'ゲストユーザーでログインしました。'
  end

  protected

  # 退会しているかを判断するメソッド
  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password]) && @user.is_deleted
      flash[:alert] = "このアカウントは退会済みです。"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :shelter]
  before_action :ensure_guest_user, only: [:edit]

  def index
    @shelter_users = User.shelter.with_attached_image.includes([:image_attachment]).page(params[:page]).per(6)
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.with_attached_image.order(created_at: :desc).page(params[:page]).per(6)
  end

  # 他のユーザーが編集しようとするとトップページに遷移させる
  def edit
    redirect_to root_path
  end
  
  def update
    redirect_to root_path
  end

  def shelter
    @user = User.find(params[:user_id])
    @articles = @user.articles.with_attached_image.order(created_at: :desc).page(params[:page]).per(6)
  end

  def unsubscribe
  end

  def withdraw
    user = current_user
    user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "ゲストユーザー"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end  

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_info.html.erb
  <div>
    <div class="mt-2 mb-2">
      <%= image_tag user.get_image(200,200), class: "rounded-circle" %>
    </div>
    <p>カテゴリー：<%= user.category_i18n %></p>
    <p>名前：<%= user.nickname %></p>
    <p>フォロー数：
      <%= link_to user_followings_path(user) do %>
        <%= user.followings.count %>
      <% end %>
    </p>
    <p>フォロワー数：
      <%= link_to user_followers_path(user) do %>
        <%= user.followers.count %>
      <% end %>
    </p>
    <p>サイト登録日<%= user.created_at.strftime('%Y/%m/%d') %></p>
  <% if user.name != "ゲストユーザー" %>
    <% unless user.admin %>
      <% if user == current_user %>
        <%= link_to "会員情報変更", edit_user_registration_path, class: "btn btn-sm btn btn-primary" %>
      <% else %>
        <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-sm btn-danger" %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-sm btn-success" %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
    <%= link_to 'chatを始める', chat_path(user.id), class: "btn btn-sm btn-primary" %>
  <% end %>
  </div>

app/views/users/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-7 mt-5 offset-md-5">
      <h2>施設一覧</h2>
    </div>

    <div class="col-md-12 mt-5 d-flex justify-content-center">

    <!--テーブルの幅の横幅が足りなくなった場合に、横スクロールさせる-->
    <div class="table-responsive">
      <table class="table table-hover table-condensed">
        <thead>
          <tr>
            <th></th>
            <th>施設名称</th>
            <th>施設住所</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @shelter_users.each do |user| %>
          <tr>
          <td class="align-middle">
            <%= link_to user_shelter_path(user) do %>
              <%= image_tag user.get_image(100,100), class: "rounded-circle" %>
            <% end %>
          </td>
          <td class="align-middle">
            <%= user.name %>
          </td>
          <td class="align-middle">
            <%= user.address %>
          </td>
          <td class="align-middle">
            <%= link_to "詳細", user_shelter_path(user), class: "btn btn-success" %>
          </td>
          </tr>
          <% end %>
          <%= paginate @shelter_users %>
        </tbody>
      </table>
    </div>


    </div>
  </div>
</div>

app/views/users/shelter.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 mt-5 mb-5 d-flex justify-content-center">
      <h4>保護施設詳細</h4>
    </div>
      <div class="col-md-5 mb-5 d-flex align-items-center justify-content-center">
          <%= image_tag @user.get_image(200,200), class: "rounded-circle" %>
      </div>
      <div class="col-md-7">
        <p>施設名称：<%= @user.name %></p>
        <p>施設名称(カナ)：<%= @user.name_kana %></p>
        <p>施設住所：<%= @user.address %></p>
        <p>サイト登録日<%= @user.created_at.strftime('%Y/%m/%d') %></p>
      </div>
      
      <div class="col-md-12 mb-5 d-flex justify-content-center">
        <%= link_to "詳細", user_path(@user), class: "btn btn-sm btn-info" %>
      </div>

    </div>


  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 mt-5 ml-5 mb-5">
      <h4>ユーザー情報<i class="fas fa-user"></i></h4>
      <%= render 'user_info', user: @user %>
    </div>
    <div class="col-md-8 mt-5 mb-5">
      <h2 class="mb-4">ユーザーの投稿</h2>
          <%= render 'articles/article_outline', articles: @articles %>
          <%= paginate @articles %>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 mt-3 offset-md-3">
      <%= image_tag 'dog-unsubscribe.jpg', size: "500x400", class: "m-5" %>
    </div>
    <div class="col-md-12 mt-3 offset-md-4">
      <h2>本当に退会しますか？</h2>
      <div class="mt-5 mb-5">
        <%= link_to "退会しない", user_path(current_user), class: "btn btn-success mr-5" %>
        <%= link_to "退会する", user_withdraw_path(current_user), method: :patch, class: "btn btn-danger ml-5" %>
      </div>
    </div>
  </div>
</div>