config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :edit, :update] 
    get 'users/search', to: 'users#search'
  end

  root to: 'homes#top'
  get "home/about" => "homes#about", as: 'about'
  get 'searches/search'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'shelter' => 'users#shelter', as: 'shelter'
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'
    patch 'withdraw', to: 'users#withdraw', as: 'withdraw'
  end

  resources :articles, only: [:index, :show, :edit, :new, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy, :show]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :notifications, only: [:index, :destroy]

  resources :chats, only: [:index, :show, :create]

  # 問い合わせ
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
	validates :name, presence: true
	validates :subject, presence: true
	validates :message, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :confirm, :back, :create, :done]

  def new
    @contact = Contact.new
  end

  # 確認画面
  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      flash.now[:alert] = 'お問合せの作成に失敗しました（＊は全て記入してください）'
      render :new
    end
  end

  # 入力内容に誤りがあった場合、入力内容を保持したまま前のページに戻る
  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  # 実際に送信、ここで入力内容を保存
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end

  # 送信完了画面
  def done
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :name, :subject, :message)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-2">
<table>
  <tbody>
    <tr>
      <td class="pt-5 pb-2" style="width: 30%;">お名前</td>
      <td class="pt-5 pb-2 pl-3"><%= @contact.name %></td>
    </tr>
    <tr>
      <td class="pb-2" style="width: 30%;">メールアドレス</td>
      <td class="pb-2 pl-3"><%= @contact.email %></td>
    </tr>
    <tr>
      <td class="pb-2" style="width: 30%;">件名</td>
      <td class="pb-2 pl-3"><%= @contact.subject %></td>
    </tr>
    <tr>
      <td class="pb-2">メッセージ</td>
      <td class="pb-2 pl-3" style="white-space: pre-wrap;"><%= @contact.message %></td>
    </tr>
  </tbody>
</table>

<%= form_with model: @contact, url: contacts_path, local: true do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :subject %>
  <%= f.hidden_field :message %>
  <div><%= f.submit '送信', class: "btn btn-success mt-3 mb-3" %></div>
<% end %>

<%= form_with model: @contact, url: back_path, local: true do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :subject %>
  <%= f.hidden_field :message %>
  <div><%= f.submit '入力画面に戻る', class: "btn btn-warning mb-3" %></div>
<% end %>
    </div>
  </div>
</div>

app/views/contacts/done.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <%= image_tag 'thank-you.jpg', size: "500x400", class: "m-5" %>
      <h2 class= "mb-5">お問合せありがとうございます</h2>
    </div>
</div>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-2">
      <%= form_with model: @contact, url: confirm_path, local: true do |f| %>
        <div class="form-group mt-5 mb-2">
          <%= f.label :name, 'お名前*' %>
          <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        </div>
      
        <div class="form-group mb-2">
          <%= f.label :email, 'メールアドレス*' %>
          <%= f.email_field :email, size: '10x10', class: 'form-control' %>
        </div>
      
        <div class="form-group mb-2">
          <%= f.label :subject, '件名*' %>
          <%= f.text_field :subject, size: '10x10', class: 'form-control' %>
        </div>
      
        <div class="form-group mb-2">
          <%= f.label :message, 'メッセージ*' %>
          <%= f.text_area :message, size: '10x10', class: 'form-control' %>
        </div>
      
        <div class="mt-4 mb-5">
          <%= f.submit '入力内容確認', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>