config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :edit, :update] 
    get 'users/search', to: 'users#search'
  end

  root to: 'homes#top'
  get "home/about" => "homes#about", as: 'about'
  get 'searches/search'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'shelter' => 'users#shelter', as: 'shelter'
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'
    patch 'withdraw', to: 'users#withdraw', as: 'withdraw'
  end

  resources :articles, only: [:index, :show, :edit, :new, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy, :show]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :notifications, only: [:index, :destroy]

  resources :chats, only: [:index, :show, :create]

  # 問い合わせ
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_one_attached :image

  # いいね・コメント機能
  has_many :favorites, dependent: :destroy
  has_many :favorite_articles, through: :favorites, source: :article
  has_many :post_comments, dependent: :destroy

  # 通知機能
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy # 自分からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy # 相手からの通知

  # フォロー・フォロワー機能
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # DM機能
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  # バリデーション
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :name_kana, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :address, presence: true
  validates :category, presence: true
  validates :telephone_number, length: { in: 6..11 }

  enum category: { private_user: 0, shelter: 1 }

  # ユーザー情報変更の際に現在のパスワードはパラメーター内で不要となり、
  # かつパスワードとパスワードの確認を空とした場合、パスワードの更新はなされなくなる
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end

  # 投稿画像がない場合は"noimage.png"を表示させる
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.png')
      image.attach(io: File.open(file_path), filename: 'noimage.png', content_type: 'image/png')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # フォローする時
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外す時
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているのか判定
  def following?(user)
    followings.include?(user)
  end

  # フォロー通知
  def create_notification_follow!(current_user)
    # すでに通知が作成されているか確認
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # admin検索(カテゴリの指定なしの場合)
  def self.searches(search)
      User.where(['name LIKE ?', "%#{search}%"])
  end

  # admin検索(カテゴリの指定ありの場合)
  def self.looks(category,word)
    if category == "private_user"
      @user = User.where("name LIKE?", "%#{word}%").and(where(category: "private_user"))
    else
      @user = User.where("name LIKE?", "%#{word}%").and(where(category: "shelter"))
    end
  end
  
  def self.guest
    find_or_create_by!(name: 'ゲストユーザー', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
      user.name_kana = "ゲストユーザー"
      user.nickname = "ゲストユーザー"
      user.telephone_number = "00000000000"
      user.address = "日本"
      user.category = "private_user"
    end
  end



end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user

  def index
    @users = User.all.order(params[:sort]).with_attached_image.includes([:image_attachment]).page(params[:page]).per(6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_root_path
  end

  def search
    @category = params[:category]
    if @category != ""
      @users = User.looks(params[:category],params[:word]).order(created_at: :desc).with_attached_image.includes([:image_attachment]).page(params[:page]).per(6)
    else
      @users = User.searches(params[:word]).order(created_at: :desc).with_attached_image.includes([:image_attachment]).page(params[:page]).per(6)
    end
  end
  
  def name_kana_desc
    @users = User.all.order(params[:sort]).with_attached_image.includes([:image_attachment]).page(params[:page]).per(6)
  end


  private

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def user_params
    #admin=trueに書き換えられないようにadminをpermitに入れない
    params.require(:user).permit(:category, :name, :name_kana, :nickname, :telephone_number, :address, :is_deleted)
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # deviseでアカウント情報を変更する際に現在のパスワード入力を省くメソッド
  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  # 更新後のパスを指定。マイページに戻るように設定。
  def after_update_path_for(resource)
    user_path(@user.id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_state, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'ゲストユーザーでログインしました。'
  end

  protected

  # 退会しているかを判断するメソッド
  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password]) && @user.is_deleted
      flash[:alert] = "このアカウントは退会済みです。"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :shelter]
  before_action :ensure_guest_user, only: [:edit]

  def index
    @shelter_users = User.shelter.with_attached_image.includes([:image_attachment]).page(params[:page]).per(6)
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.with_attached_image.order(created_at: :desc).page(params[:page]).per(6)
  end

  # 他のユーザーが編集しようとするとトップページに遷移させる
  def edit
    redirect_to root_path
  end
  
  def update
    redirect_to root_path
  end

  def shelter
    @user = User.find(params[:user_id])
    @articles = @user.articles.with_attached_image.order(created_at: :desc).page(params[:page]).per(6)
  end

  def unsubscribe
  end

  def withdraw
    user = current_user
    user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "ゲストユーザー"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end  

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_search_form.html.erb
<%= form_with model: @user, url: admin_users_search_path, :method => 'get', class: "search-form" do |f| %>
<div class="input-group">
  <%= f.text_field :word %>
  <%= f.select :category, User.categories.keys.map {|k| [I18n.t("enums.user.category.#{k}"), k]}, {prompt: 'カテゴリー'} %>
  <span class="input-group-btn">
  <%= f.submit '検索', class: "btn btn-success" %>
  </span>
</div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 mt-5 d-flex justify-content-center">
      <h3 class="font-weight-bold"><%= @user.name %> 様の会員情報編集</h3>
    </div>
    <div class="col-md-12 mt-5 d-flex justify-content-center">
      <%= form_with model: @user, url:admin_user_path, local: true do |f| %>
      <div class="table-responsive">
        <table class="table table-hover table-condensed">
          <tr>
            <td class="font-weight-bold">会員ID</td>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <td class="font-weight-bold">カテゴリー</td>
            <td>
              <%= f.radio_button :category, "private_user", checked: "checked" %>
              <%= f.label :category, "個人ユーザー" %>
              <br>
              <%= f.radio_button :category, "shelter" %>
              <%= f.label :category, "保護施設" %>
            </td>
          </tr>
          <tr>
            <td class="font-weight-bold">氏名</td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td class="font-weight-bold">フリガナ</td>
            <td><%= f.text_field :name_kana %></td>
          </tr>
          <tr>
            <td class="font-weight-bold">住所</td>
            <td><%= f.text_field :address %></td>
          </tr>
          <tr>
            <td class="font-weight-bold">電話番号</td>
            <td><%= f.text_field :telephone_number %></td>
          </tr>
          <tr>
            <td class="font-weight-bold">メールアドレス</td>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <td class="font-weight-bold">会員ステータス</td>
            <td>
              <%= f.radio_button :is_deleted, "false" %>
              <%= f.label :is_deleted, "有効" %>
              <%= f.radio_button :is_deleted, "true" %>
              <%= f.label :is_deleted, "退会" %>
            </td>
          </tr>
        </table>
      </div>
      <div class="mb-3">
        <%= f.submit "変更を保存", class: 'btn btn-success' %>
      </div>
      <div class="mb-5">
        <%= link_to "戻る", admin_root_path, class: 'btn btn-secondary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 mt-5 d-flex justify-content-center">
      <h2>登録ユーザー　一覧</h2>
    </div>
    <div class="col-md-12 mt-3 right">
      <%= render 'admin/users/search_form' %>
    </div>
    <div class="col-md-12 mt-3 offset-md-1">
      <%= paginate @users %>
    </div>
    <div class="col-md-12 mt-3 right">
      <%= link_to "新しい順", admin_users_path(sort: 'created_at DESC') %>
      |
      <%= link_to "古い順", admin_users_path(sort: 'created_at ASC') %>
    </div>
    <div class="col-md-12 mt-2 d-flex justify-content-center">
    <!--テーブルの幅の横幅が足りなくなった場合に、横スクロールさせる-->
    <div class="table-responsive">
      <table class="table table-hover table-condensed">
        <thead>
          <tr>
            <th></th>
            <th>名前</th>
            <th>名前（カナ）</th>
            <th>ニックネーム</th>
            <th>住所</th>
            <th>電話番号</th>
            <th>ユーザー詳細</th>
            <th>ステータス</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
          <tr>
          <td class="align-middle">
            <%= link_to user_shelter_path(user) do %>
              <%= image_tag user.get_image(100,100), class: "rounded-circle" %>
            <% end %>
          </td>
          <td class="align-middle">
            <%= user.name %>
          </td>
          <td class="align-middle">
            <%= user.name_kana %>
          </td>
          <td class="align-middle">
            <%= user.nickname %>
          </td>
          <td class="align-middle">
            <%= user.address %>
          </td>
          <td class="align-middle">
            <%= user.telephone_number %>
          </td>
          <td class="align-middle">
            <%= link_to "詳細", user_path(user), class: "btn btn-success" %>
          </td>
          <td class="align-middle">
            <% if user.is_deleted %>
              <p class ="font-weight-bold"><%= "退会済み" %></p>
            <% else %>
              <p class ="font-weight-bold text-success"><%= "有効会員" %></p>
            <% end %>
          </td>
          <td class="align-middle">
            <%  unless user.admin %>
              <%= link_to "編集", edit_admin_user_path(user), class: "btn btn-warning" %>
            <% end %>
          </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>


    </div>
  </div>
</div>

app/views/admin/users/search.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 mt-5 d-flex justify-content-center">
      <h2>登録ユーザー　一覧</h2>
    </div>
    <div class="col-md-12 mt-3 right">
      <%= render 'admin/users/search_form' %>
    </div>
    <div class="col-md-12 mt-3 offset-md-1">
      <%= paginate @users %>
    </div>
    <div class="col-md-12 mt-2 d-flex justify-content-center">
    <!--テーブルの幅の横幅が足りなくなった場合に、横スクロールさせる-->
    <div class="table-responsive">
      <table class="table table-hover table-condensed">
        <thead>
          <tr>
            <th></th>
            <th>名前</th>
            <th>名前（カナ）</th>
            <th>ニックネーム</th>
            <th>住所</th>
            <th>電話番号</th>
            <th>ユーザー詳細</th>
            <th>ステータス</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
          <tr>
          <td class="align-middle">
            <%= link_to user_shelter_path(user) do %>
              <%= image_tag user.get_image(100,100), class: "rounded-circle" %>
            <% end %>
          </td>
          <td class="align-middle">
            <%= user.name %>
          </td>
          <td class="align-middle">
            <%= user.name_kana %>
          </td>
          <td class="align-middle">
            <%= user.nickname %>
          </td>
          <td class="align-middle">
            <%= user.address %>
          </td>
          <td class="align-middle">
            <%= user.telephone_number %>
          </td>
          <td class="align-middle">
            <%= link_to "詳細", user_path(user), class: "btn btn-success" %>
          </td>
          <td class="align-middle">
            <% if user.is_deleted %>
              <p class ="font-weight-bold"><%= "退会済み" %></p>
            <% else %>
              <p class ="font-weight-bold text-success"><%= "有効会員" %></p>
            <% end %>
          </td>
          <td class="align-middle">
            <%  unless user.admin %>
              <%= link_to "編集", edit_admin_user_path(user), class: "btn btn-warning" %>
            <% end %>
          </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>


    </div>
  </div>
</div>