config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :edit, :update] 
    get 'users/search', to: 'users#search'
  end

  root to: 'homes#top'
  get "home/about" => "homes#about", as: 'about'
  get 'searches/search'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'shelter' => 'users#shelter', as: 'shelter'
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe'
    patch 'withdraw', to: 'users#withdraw', as: 'withdraw'
  end

  resources :articles, only: [:index, :show, :edit, :new, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy, :show]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :notifications, only: [:index, :destroy]

  resources :chats, only: [:index, :show, :create]

  # 問い合わせ
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <%= model.errors.count %>件のエラーが発生しました
    <ul>
       <button type="button" class="close" data-dismiss="alert">&times;</button>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white text-monospace pt-5 pb-4">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-md-4">
        <p>Pet Finder</p>
      </div>
      <div class="col-md-8">
        <ul class="p-0 list-unstyled">
          <li>
            <%= link_to "About", about_path, class: 'nav-link text-white-50' %>
          </li>
          <li>
            <%= link_to "お問合せ", new_contact_path, class: 'nav-link text-white-50' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="pos-f-t">
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-dark p-4">
        <h5 class="text-white h4">MENU</h5>
        <div class="navigation">
          

    <ul>
      <% if user_signed_in? %>
      <li class="button">
        <p>
          <%= link_to root_path, method: :get, class: "header-text" do %>
            Top<i class="fas fa-dog"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
          <%= link_to user_path(current_user.id), method: :get, class: "header-text" do %>
            マイページ<i class="fas fa-user"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
          <%= link_to articles_path, method: :get, class: "header-text" do %>
            掲示板<i class="fas fa-paper-plane"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
          <%= link_to users_path, method: :get, class: "header-text" do %>
            保護施設<i class="fas fa-home"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
          <%= link_to new_article_path, method: :get, class: "header-text" do %>
            新規投稿<i class="far fa-plus-square"></i>
          <% end %>
        </p>
      </li>
      <% if current_user.name != "ゲストユーザー" %>
        <% if current_user.admin == false %>
        <li class="button">
          <p>
            <%= link_to edit_user_registration_path, method: :get, class: "header-text" do %>
              会員情報編集<i class="fas fa-edit"></i>
            <% end %>
          </p>
        </li>
        <% end %>
      <% end %>
      <li class="button">
        <p>
          <%= link_to article_favorites_path(current_user.id), method: :get, class: "header-text" do %>
            いいね<i class="fas fa-thumbs-up"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
          <%= link_to user_followings_path(current_user.id), method: :get, class: "header-text" do %>
            フォロー<i class="fas fa-user-friends"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
          <%= link_to chats_path, method: :get, class: "header-text" do %>
            DM<i class="fas fa-comments"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
        <% if unchecked_notifications.any? %>
          <i class="fas fa-circle" style="color: gold;"></i>
        <% end %>
        
          <%= link_to notifications_path, method: :get, class: "header-text" do %>
            通知<i class="fas fa-bell"></i>
          <% end %>
        </p>
      </li>
      <% if current_user.admin? %>
      <li class="button">
        <p>
          <%= link_to admin_root_path, method: :get, class: "header-text" do %>
            管理者ページ<i class="fas fa-user-cog"></i>
          <% end %>
        </p>
      </li>
      <% end %>
      
      

          <% else %>

      <li class="button">
        <p>
          <%= link_to articles_path, method: :get, class: "header-text" do %>
            掲示板<i class="fas fa-paper-plane"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
          <%= link_to users_path, method: :get, class: "header-text" do %>
            保護施設<i class="fas fa-home"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
          <%= link_to about_path, method: :get, class: "header-text" do %>
            About<i class="fas fa-smile"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
          <%= link_to new_user_registration_path, method: :get, class: "header-text" do %>
            新規登録<i class="fas fa-user-plus"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
          <%= link_to new_user_session_path, method: :get, class: "header-text" do %>
            ログイン<i class="fas fa-sign-in-alt"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
          <%= link_to root_path, method: :get, class: "header-text" do %>
            Top<i class="fas fa-sign-in-alt"></i>
          <% end %>
        </p>
      </li>
      <li class="button">
        <p>
          <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class: "header-text", method: :post %>
        </p>
      </li>
      <% end %>
    </ul>
          
          
          
        </div>
        <span class="right text-muted">
          <% if user_signed_in? %>
            ようこそ、<%= current_user.nickname %>さん
          <% end %>
        </span>
        
      <div class="right">
        <%= search_form_for @q, url: searches_search_path, class: "search-form" do |f| %>
        <div class="input-group">
          <%= f.search_field :title_or_introduction_or_animal_breed_or_place_or_animal_type_cont, placeholder: 'キーワードから探す' %>
          <span class="input-group-btn">
          <%= f.submit "検索", class: "btn btn-success" %>
          </span>
          </div>
        <% end %>
      </div>
        
        
      </div>
    </div>
    <nav class="navbar navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div>
        <%= link_to root_path do %>
          <%= image_tag 'logo.png', size: '300x70' %>
        <% end %>
      </div>
      
      <span>
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: :delete, data: { confirm: 'ログアウトしますか？' }, class: "text-white" do %>
            ログアウト<i class="fas fa-sign-out-alt"></i>
          <% end %>
        <% end %>
      </span>
    </nav>
  </div>




</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetFinder</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if user_signed_in? %>
      <% if notice.present? %>
        <%= render 'layouts/flash_message' %>
      <% end %>
    <% end %>

    <!--deivseのエラー用のフラッシュメッセージを表示する時はここに書く-->
    <% if alert.present? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>

    <%= yield %>

    <span id="back">
      <a href="">
        <%= image_tag asset_path('arrow.png'), data: {"turbolinks"=>false}, class: "arrow" %>
        <!--falseでturbolinksの誤作動を防ぐ-->
      </a>
    </span>
    <%= render 'layouts/footer' %>
  </body>
</html>